{
 "title": "k8s - generic dashboard",
 "description": "Simplifies monitoring services on Kubernetes. Shows container logs, availability, resource usage and HTTP and gRPC traffic. Original ID: 14759",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   { "name": "namespace", "label": "namespace", "query": { "query": "label_values(namespace)" } },
   {
    "name": "app",
    "query": {
     "query": "label_values(kube_deployment_status_condition{namespace=\"$namespace\"}, deployment)"
    }
   },
   {
    "name": "service",
    "query": {
     "query": "label_values({namespace=\"$namespace\",deployment=\"$app\"}, container)"
    }
   },
   { "name": "metrics_filter", "label": "Metrics Filter" },
   { "name": "text" },
   { "name": "regex" },
   { "name": "exclude_text" },
   { "name": "exclude_regex" },
   { "name": "logs_filter", "label": "Logs Filter" }
  ]
 },
 "panels": [
  {
   "title": "Logs",
   "type": "row",
   "description": "Logs reported by the main container (without sidecars)",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 }
  },
  {
   "title": "Messages",
   "type": "logs",
   "gridPos": { "h": 6, "w": 18, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "{namespace=\"$namespace\", app=~\"($app)\"} |= \"$text\" |~ \"$regex\""
    }
   ]
  },
  {
   "title": "Rate",
   "type": "timeseries",
   "description": "Rate of log messages",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(count_over_time({namespace=\"$namespace\", app=~\"($app)\"}[10m])) by (level)",
     "legendFormat": "{{level}}"
    }
   ]
  },
  { "title": "Availability", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 } },
  {
   "title": "Uptime",
   "type": "gauge",
   "description": "Average uptime of the service in the selected time range",
   "gridPos": { "h": 3, "w": 2, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg_over_time(\n  min(ceil(\n    kube_deployment_status_replicas_available{namespace=\"$namespace\",deployment=~\"($app)\"} /\n    kube_deployment_status_replicas{namespace=\"$namespace\",deployment=~\"($app)\"}\n  ))\n[$__range:1m]) or\navg_over_time(\n  min(ceil(\n    kube_statefulset_status_replicas_ready{namespace=\"$namespace\",statefulset=~\"($app)\"} /\n    kube_statefulset_status_replicas{namespace=\"$namespace\",statefulset=~\"($app)\"}\n  ))\n[$__range:1m])"
    }
   ]
  },
  {
   "title": "Replicas healthy",
   "type": "state-timeline",
   "description": "Timeline showing when how many of the desired replicas were healthy",
   "gridPos": { "h": 3, "w": 10, "x": 2, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "max by(deployment) (\n  kube_deployment_status_replicas_available{namespace=\"$namespace\",deployment=~\"($app)\"} /\n  kube_deployment_status_replicas{namespace=\"$namespace\",deployment=~\"($app)\"}\n) or\nmax by(statefulset) (\n  kube_statefulset_status_replicas_ready{namespace=\"$namespace\",statefulset=~\"($app)\"} /\n  kube_statefulset_status_replicas{namespace=\"$namespace\",statefulset=~\"($app)\"}\n)",
     "legendFormat": " "
    }
   ]
  },
  {
   "title": "Restarts",
   "type": "timeseries",
   "description": "Timeline showing when container restarts occurred",
   "gridPos": { "h": 3, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "clamp_max(increase(kube_pod_container_status_restarts_total{namespace=\"$namespace\",pod=~\"($app).*\"}[$__rate_interval]) > 0, 1)"
    }
   ]
  },
  {
   "title": "Versions",
   "type": "timeseries",
   "description": "Running versions (Docker image tags) over time.",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 11 },
   "targets": [
    {
     "expr": "max by(version,container) (label_replace(kube_pod_container_info{namespace=\"$namespace\",pod=~\"($app).*\"}, \"version\", \"$1\", \"image\", \".*:(.*)\"))",
     "legendFormat": "{{container}}:{{version}}"
    }
   ]
  },
  { "title": "Resources", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 } },
  {
   "title": "Memory usage",
   "type": "timeseries",
   "description": "Memory usage of the main container (without sidecars)",
   "gridPos": { "h": 7, "w": 13, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "max by(pod) (container_memory_working_set_bytes{namespace=\"$namespace\",pod=~\"($app).*\"}) != 0",
     "legendFormat": "{{pod}}"
    },
    {
     "expr": "min(kube_pod_container_resource_requests{resource=\"memory\",namespace=\"$namespace\",pod=~\"($app).*\"})",
     "legendFormat": "Request"
    },
    {
     "expr": "min(kube_pod_container_resource_limits{resource=\"memory\",namespace=\"$namespace\",pod=~\"($app).*\"})",
     "legendFormat": "Limit"
    }
   ]
  },
  {
   "title": "CPU usage",
   "type": "timeseries",
   "description": "CPU usage of the main container (without sidecars)",
   "gridPos": { "h": 7, "w": 11, "x": 13, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "(sum by (pod) (increase(container_cpu_cfs_throttled_periods_total{namespace=\"$namespace\",pod=~\"($app).*\"}[$__rate_interval])) > bool 0)\n* min by(pod) (kube_pod_container_resource_limits{resource=\"cpu\",namespace=\"$namespace\",pod=~\"($app).*\"}) != 0\nor\nmax by(pod) (rate(container_cpu_usage_seconds_total{namespace=\"$namespace\",pod=~\"($app).*\"}[$__rate_interval])) != 0",
     "legendFormat": "{{pod}}"
    },
    {
     "expr": "min(kube_pod_container_resource_requests{resource=\"cpu\",namespace=\"$namespace\",pod=~\"($app).*\"})",
     "legendFormat": "Request"
    },
    {
     "expr": "min(kube_pod_container_resource_limits{resource=\"cpu\",namespace=\"$namespace\",pod=~\"($app).*\"})",
     "legendFormat": "Limit"
    }
   ]
  },
  { "title": "HTTP", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 23 } },
  {
   "title": "Response times",
   "type": "heatmap",
   "description": "Distribution of response times as measured by ingress controller",
   "gridPos": { "h": 6, "w": 13, "x": 0, "y": 24 },
   "targets": [
    {
     "expr": "sum by(le) (increase(nginx_ingress_controller_response_duration_seconds_bucket{exported_namespace=\"$namespace\",exported_service=~\"($app)\"}[$__rate_interval])) or\nsum by(le) (increase(istio_request_duration_milliseconds_bucket{destination_service_namespace=\"$namespace\",destination_service_name=~\"($app)\",reporter=\"source\"}[$__rate_interval]))",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Status codes",
   "type": "timeseries",
   "description": "Request count by HTTP status code as measured by ingress controller",
   "gridPos": { "h": 6, "w": 11, "x": 13, "y": 24 },
   "targets": [
    {
     "expr": "sum by(method, status) (rate(nginx_ingress_controller_requests{exported_namespace=\"$namespace\",exported_service=~\"($app)\"}[$__rate_interval])) or\nsum by(response_code) (rate(istio_requests_total{destination_service_namespace=\"$namespace\",destination_service_name=~\"($app)\",reporter=\"source\"}[$__rate_interval]))",
     "legendFormat": "{{method}}: {{status}}"
    }
   ]
  }
 ]
}